In [4]:
import numpy as np
import pandas as pd
import plotly.express as px
from google.colab import drive
drive.mount('/content/drive')

In [125]:
data1 = pd.read_csv('/content/drive/My Drive/index_1.csv')
data2 = pd.read_csv('/content/drive/My Drive/index_2.csv')
data = pd.concat([data1, data2], ignore_index=True)

In [126]:
data.columns

Index(['date', 'datetime', 'cash_type', 'card', 'money', 'coffee_name'], dtype='object')

In [127]:
print(data['coffee_name'].unique())

['Latte' 'Hot Chocolate' 'Americano' 'Americano with Milk' 'Cocoa'
 'Cortado' 'Espresso' 'Cappuccino' 'Tea' 'Chocolate with coffee'
 'Chocolate with milk' 'Coffee with Irish whiskey'
 'Irish whiskey with milk' 'Double Irish whiskey' 'Double espresso'
 'Americano with milk' 'Double espresso with milk'
 'Caramel with Irish whiskey' 'Super chocolate' 'Double vanilla'
 'Mochaccino' 'Caramel with chocolate' 'Irish whiskey' 'Caramel coffee'
 'Vanilla with Irish whiskey' 'Chocolate' 'Caramel with milk'
 'Coffee with chocolate' 'Irish with chocolate' 'Vanilla coffee'
 'Double ristretto' 'Hot milkshake' 'Double chocolate' 'Caramel']

In [129]:
data['cash_type'].unique()

array(['card', 'cash'], dtype=object)

In [61]:
def filter(data=data, type=type):
  return data[data['coffee_name'] == type]['date', 'cash_type', 'card', 'money']
#latte
latte = filter(data,'Latte')
#'Hot Chocolate'
hc = filter(data,'Hot Chocolate')
#'Americano'
americano = filter(data,'Americano')
#'Americano with Milk'
AWM =  filter(data,'Americano')
#'Cocoa'
cocoa=filter(data,'Cocoa')
#'Cortado'
cortado = filter(data,'Cortado')
#'Espresso'
expresso = filter(data,'Expresso')
#'Cappuccino'
capp = filter(data,'Cappuccino')

In [133]:
data.groupby('coffee_name')['money'].sum().sort_values(ascending=False)

coffee_name
Latte                         28658.30
Americano with Milk           25269.12
Cappuccino                    18514.14
Americano                     15437.26
Hot Chocolate                 10172.46
Cocoa                          8678.16
Cortado                        7534.86
Espresso                       3187.28
Americano with milk            1100.00
Irish whiskey                   525.00
Coffee with Irish whiskey       464.00
Irish whiskey with milk         405.00
Double Irish whiskey            336.00
Chocolate with milk             324.00
Tea                             240.00
Caramel with Irish whiskey      224.00
Super chocolate                 168.00
Chocolate with coffee           150.00
Mochaccino                      150.00
Irish with chocolate            135.00
Caramel with chocolate          112.00
Vanilla with Irish whiskey       84.00
Caramel with milk                75.00
Double espresso with milk        64.00
Caramel coffee                   56.00
Double vanilla                   47.00
Hot milkshake                    30.00
Coffee with chocolate            28.00
Double espresso                  27.00
Double ristretto                 27.00
Vanilla coffee                   27.00
Chocolate                        25.00
Double chocolate                 25.00
Caramel                          22.00
Name: money, dtype: float64

In [138]:
latte

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
12,2024-03-02,2024-03-02 10:30:35.668,cash,NaN,40.00,Latte
18,2024-03-03,2024-03-03 10:10:43.981,cash,NaN,40.00,Latte
19,2024-03-03,2024-03-03 10:27:18.561,card,ANON-0000-0000-0015,38.70,Latte
...,...,...,...,...,...,...
3615,2025-03-21,2025-03-21 17:22:49.875,card,ANON-0000-0000-1191,35.76,Latte
3616,2025-03-21,2025-03-21 18:52:12.666,card,ANON-0000-0000-0507,35.76,Latte
3627,2025-03-22,2025-03-22 16:26:59.766,card,ANON-0000-0000-1274,35.76,Latte
3630,2025-03-23,2025-03-23 10:07:11.278,card,ANON-0000-0000-1196,35.76,Latte
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte